/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Clock;
import Classes.Mothership;
import Classes.SensorMonitor;
import Classes.SensorStation;
import File.serialize;
import static GUI.MainSensorStation.waitTime;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Observer;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Akila Jayaaasinghe
 */
public class HomeViewData extends javax.swing.JInternalFrame {
public static String globalStationId;
Mothership mother=new Mothership("Kaduwela", serialize.getAllSensorStations());

    /**
     * Creates new form Home
     */
    public HomeViewData() {
        initComponents();
//       load();
//        tableLoad();
       
    }
 
    
    public void tableLoad(){
    DefaultTableModel model=(DefaultTableModel) dataTable.getModel();
     model.setRowCount(0);
    
                for(SensorStation station:mother.getSensorStation()){
                        model.addRow(new Object[]{station.getStationID(),station.getName()});
                    }  
    }
//    dsasd
  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dataTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        searchTextBox = new javax.swing.JTextField();
        stationRadioButton = new javax.swing.JRadioButton();
        monitorRadioButton = new javax.swing.JRadioButton();
        sensorTypeRadioButton = new javax.swing.JRadioButton();
        sensorNameRadioButton = new javax.swing.JRadioButton();

        setBorder(null);
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(680, 480));
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(680, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(680, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jLabel15.setText("A step towards Smart Sri Lanka");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, 171, -1));

        dataTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sensor ID", "Sensor Name", "Sensor Type", "Sensor Monitor", "Sensor Station"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        dataTable.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(dataTable);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 640, 348));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Search");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        searchTextBox.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        searchTextBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTextBoxActionPerformed(evt);
            }
        });
        jPanel1.add(searchTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 190, 30));

        buttonGroup1.add(stationRadioButton);
        stationRadioButton.setText("By Sensor Station");
        jPanel1.add(stationRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, -1, -1));

        buttonGroup1.add(monitorRadioButton);
        monitorRadioButton.setText("By Sensor Monitor");
        monitorRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monitorRadioButtonActionPerformed(evt);
            }
        });
        jPanel1.add(monitorRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        buttonGroup1.add(sensorTypeRadioButton);
        sensorTypeRadioButton.setText("By Sensor Type");
        jPanel1.add(sensorTypeRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, -1, -1));

        buttonGroup1.add(sensorNameRadioButton);
        sensorNameRadioButton.setText("By Sensor Name");
        jPanel1.add(sensorNameRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTextBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTextBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTextBoxActionPerformed

    private void monitorRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monitorRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monitorRadioButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable dataTable;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton monitorRadioButton;
    private javax.swing.JTextField searchTextBox;
    private javax.swing.JRadioButton sensorNameRadioButton;
    private javax.swing.JRadioButton sensorTypeRadioButton;
    private javax.swing.JRadioButton stationRadioButton;
    // End of variables declaration//GEN-END:variables
}
