/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Classes.Data;
import Classes.Location;
import Classes.Mothership;
import Classes.Sensor;
import Classes.SensorMonitor;
import Classes.SensorStation;
import static File.Map.readmap;
import File.serialize;
import static GUI.HomeMonitor.globalMonitorId;
import static GUI.HomeStation.globalStationId;
import com.teamdev.jxbrowser.chromium.Browser;
import com.teamdev.jxbrowser.chromium.swing.BrowserView;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Akila Jayasinghe
 */
public class UpdateMointor extends javax.swing.JInternalFrame {
Mothership mother=new Mothership("Kaduwela", serialize.getAllSensorStations());    
SensorStation station = mother.findSensorStation(globalStationId);
SensorMonitor m=station.getASensorMonitor(globalMonitorId);
 List<Double> coords= new ArrayList<Double>();
String x[]=null;
boolean select=false;
    /**
     * Creates new form Home
     */
    public UpdateMointor() {

        initComponents();
      
      idTextBox.setText(m.getSensorMonitorID());
      intervalTextBox2.setText(Long.toString(m.getIntereval()));
      if(m.getIsActive()){
        activeRadioButton.setSelected(true);
    }
      else{
          deactiveRadioButton.setSelected(true);
      }
      
      coords=m.getCoords();
//      
      Location l =new Location(coords.get(0), coords.get(1));
      String s=l.toAdress();
      locationTextBox.setText(s);
      nameTextBox.setText(m.getName());
      
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        updateButton = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idTextBox = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        activeRadioButton = new javax.swing.JRadioButton();
        deactiveRadioButton = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        locationTextBox = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        setLocationButton = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        intervalTextBox2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nameTextBox = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(680, 480));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 1, 10)); // NOI18N
        jLabel15.setText("A step towards Smart Sri Lanka");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 171, -1));

        updateButton.setBackground(new java.awt.Color(102, 48, 142));
        updateButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        updateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                updateButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                updateButtonMouseExited(evt);
            }
        });
        updateButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\CSSD-asignment\\Images\\Available Updates_25px.png")); // NOI18N
        updateButton.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 50));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Update Monitor");
        updateButton.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jPanel1.add(updateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 150, -1));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Sensor ID");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 120, 30));

        idTextBox.setEditable(false);
        jPanel1.add(idTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 230, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Status");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 120, 30));

        buttonGroup1.add(activeRadioButton);
        activeRadioButton.setText("Active");
        jPanel1.add(activeRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        buttonGroup1.add(deactiveRadioButton);
        deactiveRadioButton.setText("Deactive");
        jPanel1.add(deactiveRadioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Update Monitor");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        locationTextBox.setEditable(false);
        jPanel1.add(locationTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 260, 230, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Location");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 120, 30));

        setLocationButton.setBackground(new java.awt.Color(102, 81, 181));
        setLocationButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        setLocationButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                setLocationButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                setLocationButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                setLocationButtonMouseExited(evt);
            }
        });
        setLocationButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\CSSD-asignment\\Images\\Marker_20px.png")); // NOI18N
        setLocationButton.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 30));

        jPanel1.add(setLocationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, 20, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Interval");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 120, 30));

        intervalTextBox2.setText("0");
        intervalTextBox2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                intervalTextBox2KeyTyped(evt);
            }
        });
        jPanel1.add(intervalTextBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 230, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Sensor Name");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 120, 30));
        jPanel1.add(nameTextBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, 230, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseEntered
        evt.getComponent().setBackground(new Color(80, 80, 125));
    }//GEN-LAST:event_updateButtonMouseEntered

    private void updateButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseExited
        evt.getComponent().setBackground(new Color(102, 48, 142));
    }//GEN-LAST:event_updateButtonMouseExited


    private void updateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateButtonMouseClicked
        
        if("".equals(nameTextBox.getText()) || "".equals(locationTextBox.getText())){
            JOptionPane.showMessageDialog(null,"Please fill all fields");
        }
                else{
                Boolean status;
                if(activeRadioButton.isSelected()){
                    status=true;
                }
                else{
                    status=false;
                }

                if(select){
                    coords.set(0,Double.parseDouble(x[0]));
                    coords.set(1,Double.parseDouble(x[1]));
                }

                mother.removeSensorStation(globalStationId);
                station.removeSensorMonitor(m);
                m.setCoords(coords);
                m.setIsActive(status);
                m.setName(nameTextBox.getText());
                station.addNewSensorMonitor(m);
               boolean check= mother.addNewSensorStation(station);


                if(check){
                    JOptionPane.showMessageDialog(null,"Sensor Monitor Update Successfully");
                    HomeMonitor h = new HomeMonitor();
                    JDesktopPane n =this.getDesktopPane();
                    n.removeAll();
                }
                else{
                    JOptionPane.showMessageDialog(null,"Sensor Monitor Update Fail");
                }
        }
    }//GEN-LAST:event_updateButtonMouseClicked

    private void setLocationButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setLocationButtonMouseClicked
        // TODO add your handling code here:
        mapload();
    }//GEN-LAST:event_setLocationButtonMouseClicked

    private void setLocationButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setLocationButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_setLocationButtonMouseEntered

    private void setLocationButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_setLocationButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_setLocationButtonMouseExited

    private void intervalTextBox2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_intervalTextBox2KeyTyped
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        String s=intervalTextBox2.getText();
         
         if(!(Character.isDigit(c))||(c==com.sun.glass.events.KeyEvent.VK_BACKSPACE) || (c== com.sun.glass.events.KeyEvent.VK_DELETE))
         {
             evt.consume();
         }
    }//GEN-LAST:event_intervalTextBox2KeyTyped

public void mapload(){
    Browser browser = new Browser();
    BrowserView view = new BrowserView(browser);

    JFrame m = new JFrame();
        m.add(view).addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                        int y=JOptionPane.showConfirmDialog(null,"Add this Location ?","Location",JOptionPane.YES_NO_OPTION);
                        if(y==0){
                            x=readmap();
                            Location l =new Location(Double.parseDouble(x[0]), Double.parseDouble(x[1]));
                            String s=l.toAdress();
                            locationTextBox.setText(s);
                            m.dispose();
                            select = true;
                        }
                        
            }
        });
        
        m.setSize(920,580);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        m.setLocation(dim.width/2-m.getSize().width/2, dim.height/2-m.getSize().height/2);
        m.setVisible(true);
        

    browser.loadURL("http://localhost:4200/");
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton activeRadioButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton deactiveRadioButton;
    private javax.swing.JTextField idTextBox;
    private javax.swing.JTextField intervalTextBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField locationTextBox;
    private javax.swing.JTextField nameTextBox;
    private javax.swing.JPanel setLocationButton;
    private javax.swing.JPanel updateButton;
    // End of variables declaration//GEN-END:variables
}
